# Generated by Django 5.0.3 on 2024-06-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balloon_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balloonflight',
            name='from_to',
        ),
        migrations.AddField(
            model_name='balloonflight',
            name='from_airport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='balloonflight',
            name='to_airport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
