# Generated by Django 5.0.3 on 2024-06-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_bands'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_of_bands',
            field=models.IntegerField(default=0),
        ),
    ]
