# Generated by Django 5.0.3 on 2024-06-05 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('founding_year', models.IntegerField()),
                ('website', models.URLField()),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='photos/')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('year_of_publishing', models.IntegerField()),
                ('num_pages', models.IntegerField()),
                ('dimensions', models.CharField(max_length=10)),
                ('book_cover_type', models.CharField(choices=[('SF', 'Soft'), ('HR', 'Hard')], max_length=3)),
                ('category', models.CharField(choices=[('RM', 'Romance'), ('TH', 'Thriller'), ('BI', 'Biography'), ('CL', 'Classic'), ('DR', 'Drama'), ('HR', 'Historical')], max_length=3)),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.publishinghouse')),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('M', 'Main'), ('S', 'Secondary')], max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.book')),
            ],
        ),
        migrations.CreateModel(
            name='PublishingHouseAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.author')),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.publishinghouse')),
            ],
        ),
    ]
